# This is a basic workflow to help you get started with Actions

name: s3


on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : install Dependencies
        run : npm i 
        
      - name : build
        run : npm run build:all
        
      - name : get build_version
        run : script/set_version.sh
        
      - name : checking
        run : echo ${{ steps.package-version.outputs.current-version}}
