# This is a basic workflow to help you get started with Actions

name: s3

on:
  push:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

     #https://github.com/marketplace/actions/get-current-package-version
     #get version use package.json
      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.2.3  

      - name : install Dependencies
        run : npm i 
        
      - name : build
        run : npm run build:all
        
      - name : checking
        run : echo ${ { steps.package-version.outputs.current-version } }
